--- # Audit servers and Email back the results
- hosts: all
  user: ec2-user
  gather_facts: no
  connection: ssh
  sudo: yes
  tasks:
    - copy: src=/home/ansible/sony-cis-ansible/roles/report/files/cis-cat-full.zip dest=/home/ec2-user/cis-cat-full.zip owner=ec2-user group=ec2-user mode=0644 backup=yes
    - unarchive: src=/home/ec2-user/cis-cat-full.zip dest=/home/ec2-user owner=ec2-user group=ec2-user copy=no
    - cron: name="sme-run audit" minute="45" hour="*" user="root" job="/home/ec2-user/cis-cat-full/report.sh >> /home/ec2-user/cis-cat-full/cis-cat.log"
