--- # Audit servers and Email back the results
- hosts: webservers
  user: ec2-user
  gather_facts: no
  connection: ssh
  sudo: yes
  tasks:
    - copy: src=/home/ansible/report/cis-cat-full.zip dest=/home/ec2-user/cis-cat-full.zip owner=ec2-user group=ec2-user mode=0644 backup=yes
    - unarchive: src=/home/ec2-user/cis-cat-full.zip dest=/home/ec2-user owner=ec2-user group=ec2-user copy=no
    - command: /home/ec2-user/cis-cat-full/report.sh chdir=/home/ec2-user
